require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisplayCopName: true
  Include:
    - '**/*.rb'
    - '**/Gemfile'
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/**/*'
  TargetRubyVersion: 3.2

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

Style/FrozenStringLiteralComment:
  Enabled: false
